$(eval $(call addlib_s,libukrusttest,$(CONFIG_LIBUKRUSTTEST)))

CINCLUDES-$(CONFIG_LIBUKRUSTTEST) += -I$(LIBUKRUSTTEST_BASE)/include

LIBUKRUSTTEST_FLAGS = --target=$(LIBUKRUST_BASE)/target.json --edition=2021 \
	-Cpanic=abort -Cembed-bitcode=n -Clto=n -Crpath=n \
	-Cforce-unwind-tables=n -Ccodegen-units=1 \
	-Zbinary_dep_depinfo=y -Csymbol-mangling-version=v0 \
	-Dunsafe_op_in_unsafe_fn \
	--crate-type rlib

$(LIBUKRUSTTEST_BUILD)/ukrusttest.o: $(LIBUKRUST_BUILD)/ukrust_sys.o
	$(call build_cmd, RUSTC, libukrusttest, $(notdir $@), \
	$(RUSTC) $(LIBUKRUSTTEST_FLAGS)  \
	--out-dir $(LIBUKRUSTTEST_BUILD) -L $(LIBUKRUST_BUILD) --extern ukrust_sys --extern alloc --extern core -A dead_code \
		--emit=dep-info --emit=obj=$(LIBUKRUSTTEST_BUILD)/ukrusttest.o --emit=metadata=$(LIBUKRUSTTEST_BUILD)/libukrusttest.rmeta \
		-A unused_doc_comments --crate-name ukrusttest $(LIBUKRUSTTEST_BASE)/src/lib.rs)

LIBUKRUSTTEST_OBJS-y += $(LIBUKRUSTTEST_BUILD)/ukrusttest.o
# LIBUKRUSTTEST-SRCS-y += $(LIBUKRUSTTEST_BASE)/rusttest_glue.c
# LIBUKRUSTTEST-SRCS-y += $(LIBUKRUSTTEST_BASE)/src/lib.rs
# LIBUKRUSTTEST_OBJS-y += $(LIBUKRUSTTEST_BUILD)/libukrusttest.a
